### ISSUE TITLE
Request to Approach on Possible Drawing Mandala Modification and Enhancement

### ISSUE THREAD

**Issue by wenghong216** [Garciat/drawmandala.app#6]
Garciat, couldn't find your contact information anywhere and have no choice but to approach you here. Is it possible that we can make a connection to discuss on the modification and enhancement that will need your help?

**Comment by Garciat** [comment]
Hi @wenghong216. Sorry for the late reply. What do you have in mind?

**Comment by wenghong216** [comment]
Hi @Garciat , we are thinking of building mandala drawing app for our member and it should be available for desktop and mobile view and thinking we could use your service. Is it possible that we discuss this through email?

**Comment by Garciat** [comment]
@wenghong216 you may provide an email I can address to, or any other means to contact you

**Comment by wenghong216** [comment]
Hi @Garciat , if possible please contact me through this email neohwh@lucywalkerjewellery.com and I'll let you know more on the project. Thank you
